exports.testTopics = ['action','drama','fantasy','sci-fi','horror','crime'];

exports.testeStories = {
  action: "After John returns to New York, Santino opens a $7 million contract for John's death under the guise of avenging his sister, leading numerous assassins to unsuccessfully attack John. Eventually, Cassian confronts John in the subway. John wins the fight and mortally wounds Cassian, but leaves him alive out of professional respect. Injured and desperate, John seeks help from an underground crime lord known as the Bowery King, whose subordinates treat John's injuries and guide him to an art museum where Santino is holding a gala. John dispatches Santino's henchmen and chases Santino through a mirror exhibit in the museum, where he kills the rest of Santino's men and kills Ares in a final fight. He pursues Santino, who flees to the Continental, where he smugly makes it clear that he intends to remain indefinitely in its sanctuary and he will never cancel Wick's bounty. Despite Winston's warnings, John shoots and kills Santino in the Continental lounge.", 
  drama: "The next day, while repairing Dalton's TV antenna, Booth reminisces about a sparring contest he had with Bruce Lee on the set of The Green Hornet which resulted in Booth being fired. Meanwhile, Charles Manson stops by the Polanski residence looking for producer Terry Melcher, who used to live there, but is turned away by Jay Sebring. Tate goes for errands and stops at a movie theater to watch herself in the film The Wrecking Crew. Dalton is cast to play the villain in the pilot of Western television series Lancer and strikes up a conversation with his eight-year-old co-star, Trudi Fraser. During filming, Dalton struggles to remember his lines and suffers a violent breakdown later in his trailer as a result. He subsequently delivers a strong performance that impresses Fraser and the director, Sam Wanamaker, bolstering his confidence.",

  fantasy: "Thranduil and an Elf army arrive in Dale and form an alliance with Bard in order to reclaim a treasure once withheld from them by Thrór. Bard goes to the mountain and asks Thorin for the share of gold that he had previously promised the people of Laketown, but Thorin refuses. Gandalf arrives at Dale to warn Bard and Thranduil of the threat posed by Azog, but Thranduil dismisses him. Bilbo sneaks out of Erebor to hand the Arkenstone over to Thranduil and Bard so that they can trade it for the treasures they were promised and prevent a battle. When Bard's and Thranduil's armies gather at the gates of Erebor, offering to trade the Arkenstone for the promised treasures, Thorin angrily refuses to believe they have the Arkenstone until Bilbo admits giving it away and chides Thorin for letting greed cloud his judgement. Outraged by what he sees as betrayal, Thorin nearly kills Bilbo, but Gandalf appears and shames Thorin into releasing Bilbo. Thorin's cousin Dáin arrives with his Dwarf army, and a battle of Dwarves against Elves and Men ensues, until Wereworms emerge from the ground, releasing Azog's army from their tunnels. With the Orcs outnumbering Dáin's army, Thranduil and Bard's forces, along with Gandalf and Bilbo, join the battle, fighting the Orcs. However, a second front is opened when many Orcs, Ogres, and Trolls attack Dale, forcing Bard to withdraw his forces to defend the city, while Alfrid takes a pile of gold and flees from Dale to his ultimate fate.",

  sci_fi: "Rey retrieves the Wayfinder from the remains of the second Death Star, but she is met by Kylo, who destroys the Wayfinder and duels her. In a dying act, Leia calls to Kylo through the Force, distracting him as Rey impales him. Sensing Leia's death, Rey heals Kylo and takes his ship to exile herself on Ahch-To. There, Luke's Force spirit encourages Rey to face Palpatine and gives her Leia's lightsaber. Rey leaves for Exegol in Luke's X-wing fighter, using the Wayfinder from Kylo's ship. Meanwhile, Kylo converses with a memory of his father, Han Solo; he throws away his lightsaber and reclaims his identity as Ben Solo. Sensing Leia's death and Ben's return, Palpatine sends one of his superlaser-equipped Star Destroyers to obliterate Kijimi as a show of force. The Resistance, led by Poe and Finn, prepare to attack Palpatine's armada.",

  horror: "Beverly Marsh, a girl bullied over rumors of promiscuity, also joins the group; both Bill and Ben develop feelings for her. Later, the group befriends orphan Mike Hanlon after defending him from Bowers. Each member of the group has encountered terrifying manifestations of the same menacing clown who attacked Georgie: a headless undead boy, a sink that spews blood only children can see, a diseased and rotting leper, a disturbing painting come to life, Mike's parents burning alive, and a frightening phantom of Georgie. Now calling themselves \"The Losers Club\", they realize they are all being stalked by the same entity, which they refer to as \"It\". They determine that It assumes the appearance of what they fear most, awakening every 27 years to feed on the children of Derry before returning to hibernation, and moves about by using the sewer lines, which all lead to an old stone well hidden under an abandoned house. After another attack by Pennywise, the group ventures to the house to confront It, only to be separated and terrorized. As Pennywise gloats to Bill about Georgie, the Losers regroup and Beverly impales Pennywise through the head, forcing the clown to retreat. The group flees the house and begins to splinter, with only Bill and Beverly resolute in fighting It.",

  crime: "Davis and Burns manage to catch up to Michael and Ray; after accidentally killing a civilian, Ray is fatally wounded by Davis. Michael holds Burns at gunpoint, telling Davis about the drives and how suspicious everything is, before escaping. Burns chastises Davis for letting Michael escape despite Davis' reputation. Michael hides in a hotel room, where he unlocks the contents of the drive and realizes that McKenna's precinct was involved in trafficking the drugs from the winery and earning profits for it, and that all seven of the cops he and Ray had killed in the shootout had been corrupt. After another chase where Michael abandons his money, Davis manages to corner him in a subway train and convinces him to surrender, promising to keep him alive. Michael is suddenly shot by Burns, who had also boarded the train and claimed that she thought Michael was still holding Davis at gunpoint. Davis berates her for shooting Michael, who secretly hands over the drives, along with the password, to Davis before dying. As the police congratulate the two for their efforts, Davis discovers that Burns had contacted Kelly before Adi's apartment was raided.",

};
